### ISSUE TITLE
Feature request - Ability to force display of an image even if it doesn't seem to be a GIF

### ISSUE THREAD

**Issue by notkirito** [vilhalmer/oguri#44]
My use-case for this would be that I'm currently trying to "force" GLava to work on Wayland. What I plan to do is to trick OBS into recording into a FIFO and make `oguri` play back the fifo. Unfortunately, `oguri` doesn't recognize the FIFO as a valid GIF file:
```
File does not appear to be a GIF file
Could not open image '/home/user/glava-fifos/test.gif': File does not appear to be a GIF file
```

I've tried looking for the error in the code, and I don't see it. If I knew where to find it, I'd definitely make a PR instead of making a feature request.

edit1: This is actually very probably an A/B problem, but GLava probably won't ever be on wayland, best I could hope for is probably GIF output to a FIFO which is.. still this feature request.

**Comment by vilhalmer** [comment]
This functionality is provided by the underlying gdk-pixbuf library, not oguri. But GIF isn't just a series of frames either, so I don't think this is probably doable. However, I've recently come across [mpvpaper](https://github.com/GhostNaN/mpvpaper), which should be able to accomplish what you're trying to do since mpv can read just about any format.

**Comment by notkirito** [comment]
I see. Thanks a lot for the recommendation.
